orbs: # declare what orbs we are going to use
  node: circleci/node@4.0.0 # the node orb provides common node-related configuration 

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  build:
    executor: node/default
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - checkout  
      - run: npm install
      - run: npm run build
      - run: mkdir artifacts
      - run: tar -zcvf artifacts/build.tar.gz --exclude artifacts . 
      - run: ls -al
      - store_artifacts: 
          path: ./artifacts/build.tar.gz
          destination: build_output.tar.gz
      - run: # Run security audit.
          halt_build_on_fail: false 
          command: 
            npm audit > ./artifacts/security_report.txt || true 
      - store_artifacts: 
          path: ./artifacts/security_report.txt
          destination: security_report.txt

#  test:
#    executor: node/default
#    steps:
#      - checkout  
#      - run: npm install
#      - run: npm test 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
#      - test:
#          requires:
#            - build